### ISSUE TITLE
Use `remove` option instead of `stat`?

### ISSUE THREAD

**Issue by mambocab** [asmacdo/dotfiles#1]
Heyo!

The commands for dropping in rc files usually look before they leap -- they `stat` for a file, then if it exists, they back it up before overwriting it:

```yml
- name: Check if vimrc exists
  stat: path="{{dotfiles_user_home}}/.vimrc"
  register: vimrc_stat
  failed_when: False

- name: Backup vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.vimrc.bak"
  when: vimrc_stat.stat.exists
```

Is there any reason not to use the `removes` option on the command module? If I read [this documentation](http://docs.ansible.com/command_module.html) correctly, these commands could be replaced with

```yml
- name: Backup vimrc if one exists
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    removes: "{{dotfiles_user_home}}/.vimrc"
```

Any reason not to do that?

Also, if I read the docs correctly, the `creates` option to the Backup task makes it execute conditionally -- `.vimrc` will only be backed up no `.vimrc.bak` exists. Don't know if that's intended behavior.
